boostcampwm-2022/web21-devrank

- frontend/.eslintrc.json
- frontend/.prettierrc
- frontend eslint 및 prettier 설정 파일 추가
> chore: frontend eslint 및 prettier 설정파일 작성

- .github/labeler.yml
- .github/workflows/label.yml
labeler workflow 추가
변경사항을 인식하여 그에 맞는 라벨을 자동으로 할당해줌
> ci: add labeler workflow

- frontend/.eslintrc.js
- frontend/.prettierrc
- frontend/next.config.js
- frontend/package.json
- frontend/src/apis/auth.ts
- frontend/src/components/Footer/index.tsx
- frontend/src/components/Header/index.tsx
- frontend/src/components/common/Avatar/index.tsx
- frontend/src/components/common/Button/Button.stories.tsx
- frontend/src/components/common/Button/index.tsx
- frontend/src/components/common/Dropdown/Dropdown.stories.tsx
- frontend/src/components/common/Dropdown/DropdownItem.tsx
- frontend/src/components/common/Dropdown/index.ts
- frontend/src/components/common/Spinner/Spinner.stories.tsx
- frontend/src/components/common/Spinner/index.tsx
- frontend/src/components/common/index.ts
- frontend/src/contexts/authContext.ts
- frontend/src/hooks/useDropdown.ts
- frontend/src/pages/_app.tsx
- frontend/src/pages/_document.tsx
- frontend/src/pages/callback.tsx
- frontend/src/pages/index.tsx
- frontend/src/styles/globalStyles.ts
- frontend/src/types/index.ts
- frontend/src/utils/axiosInstance.ts
- frontend/src/utils/constants.ts
- frontend/tsconfig.eslint.json
- frontend/yarn.lock
- Github 로그인 동작 구현
- close #13
- 로딩 스피너 컴포넌트 구현
- Github 로그인 요청 로직 구현
- 로그인 여부를 저장할 Auth Context 생성
- Github 로그인 시 access token 상태 등록 및 토큰 만료시 refresh 요청 로직 추가
> Feature: 로그인 로직 구현

- frontend/src/apis/auth.ts
- frontend/src/components/Header/index.tsx
- frontend/src/components/common/Dropdown/DropdownItem.tsx
- frontend/src/hooks/index.ts
- frontend/src/hooks/useQueryData.ts
- frontend/src/pages/_app.tsx
- frontend/src/pages/callback.tsx
- frontend/src/types/index.ts
- 유저 로그아웃 동작 구현
- close #14 
- logout api 요청 함수 구현
- context로 로그인 후 유저 state를 관리하는 방법에서 tanstack-query로 서버상태를 이용하는법으로 리팩토링
- tanstack query cached data 사용 로직을 useQueryData 커스텀 훅으로 분리
- 상단바 로그아웃 버튼 클릭시 사용자 로그아웃 동작 구현
> Feature: 유저 로그아웃 구현

- backend/src/auth/auth.controller.ts
- backend/src/main.ts
- backend/src/user/user.controller.ts
- 스웨거 테스트를 위한 github oauth 페이지 redirect 메소드 추가 ( `/auth/github` )
- 스웨거 인증 헤더 설정
> Features: swagger auth

- frontend/next.config.js
- frontend/src/apis/auth.ts
- frontend/src/components/Header/index.tsx
- frontend/src/components/common/Avatar/index.tsx
- frontend/src/hooks/index.ts
- frontend/src/hooks/useQueryData.ts
- frontend/src/hooks/useRefresh.ts
- frontend/src/pages/index.tsx
- 새로 고침시 로그인 유지 구현
- close #50
- 페이지 마운트 시 token refresh를 요청하는 useRefresh훅 구현 및 적용
> Feature: 로그인 유지 구현

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
issue template에 제목에 뒤에 공백을 하나 추가해서 좀 더 작성을 용이하게 했습니다
> Chore: issue template

- backend/src/user/dto/user.dto.ts
- backend/src/user/user.service.ts
> fix: octokit/rest를 octokit/core로 통합

- backend/src/user/dto/user.dto.ts
- backend/src/user/user.controller.ts
- backend/src/user/user.schema.ts
- backend/src/user/user.service.ts
follwers score를 계산해 user schema에 저장하도록 구현했습니다
> Feature: follower score

- frontend/public/locales/en/common.json
- frontend/src/components/Header/index.tsx
- frontend/src/pages/callback.tsx
- i18n(국제화) 라우팅 적용
- close #12 
- 로그인 후 콜백시 현재 pathname으로 돌아오도록 처리
- 언어선택 드롭다운에서 언어 선택시 i18n routing 
- 영어 로그인 버튼 text Login -> LOGIN으로 수정
> Feature: i18n 설정 구현

- frontend/.storybook/main.js
- frontend/package.json
- frontend/public/icons/cube/cube-small-all.svg
- frontend/public/icons/cube/cube-small-blue.svg
- frontend/public/icons/cube/cube-small-green.svg
- frontend/public/icons/cube/cube-small-mint.svg
- frontend/public/icons/cube/cube-small-orange.svg
- frontend/public/icons/cube/cube-small-purple.svg
- frontend/public/icons/cube/cube-small-red.svg
- frontend/public/icons/cube/cube-small-yellow.svg
- frontend/src/components/Ranking/Ranking.stories.tsx
- frontend/src/components/Ranking/index.tsx
- frontend/src/components/common/Avatar/Avatar.stories.tsx
- frontend/src/components/common/Avatar/index.tsx
- frontend/src/components/common/CubeIcon/index.tsx
- frontend/src/pages/index.tsx
- frontend/src/styles/theme.ts
- frontend/src/utils/mockData.ts
- frontend/yarn.lock
메인페이지 Ranking 컴포넌트 추가
- #15
- 랭킹컴포넌트 추가
- 랭킹컴포넌트 스토리북 추가
- CubeIcon 컴포넌트 추가
- Avatar 컴포넌트 추가
- 메인페이지 랭킹컴포넌트 추가(Layout 수정 필요)
> [Feature]: 메인페이지 Ranking 컴포넌트 추가

- frontend/public/locales/en/common.json
- frontend/public/locales/ko/common.json
- frontend/src/components/Header/index.tsx
- frontend/src/pages/index.tsx
국제화 언어 표시 수정
- 국제화 언어표시 변경
- korean -> 한국어, 영어 -> English
- 랭킹 컴포넌트 명, 회 제거
> Feature: 국제화 언어 표시 수정

- frontend/src/components/Header/index.tsx
- frontend/src/components/common/Searchbar/index.tsx
로그인 시 `userData.user.avatarUrl` 을 찾을수 없다고 하던 오류 해결 
- close #74 
- 백엔드 API repsonse 변경에 따라 userData.user.avatarUrl -> userData.avatarUrl로 변경
- import 문 오타 수정
- 로그인 유지 시 헤더 로딩 추가
> Fix: 로그인 오류 수정

- frontend/.storybook/i18n.js
- frontend/.storybook/main.js
- frontend/.storybook/preview.js
- frontend/package.json
- frontend/yarn.lock
Storybook i18n 설정
- close #79
- Storybook에서 스토리에 국제화 텍스트가 알맞게 표시되게 설정
> Feature: storybook i18n

- frontend/.eslintrc.js
- frontend/tsconfig.eslint.json
- frontend/tsconfig.json
`tsconfig.eslint.json`에서 분리해 include속성에 포함하던 파일들을 tsconfig의 include에서 명시하고 `tsconfig.eslint.json`를 삭제
- `tsconfig.eslint.json` 삭제
- `tsconfig.json` 의 include속성에 `.eslintrc.js`, `next.config.js`, `next-i18next.config.js` 를 명시
> Refactor: tsconfig.eslint.json파일 tsconfig.json으로 통합

- backend/src/user/dto/response-ranking.dto.ts
- backend/src/user/dto/response-rankings.dto.ts
- backend/src/user/user.controller.ts
- backend/src/user/user.schema.ts
- backend/src/user/user.service.ts
- ranking api 작성
- defaultBranch가 없는경우 예외처림 되어야함
- graphql에 사용되는 token을 유저token으로 대체되어야함
> Feature: Ranking API 작성

- backend/src/auth/auth.controller.ts
- backend/src/auth/strategies/jwt.strategy.ts
- backend/src/auth/strategies/refresh.strategy.ts
- backend/src/auth/types/index.ts
- backend/src/user/user.controller.ts
- backend/src/user/user.repository.ts
- backend/src/user/user.schema.ts
- backend/src/user/user.service.ts
ranking에서 username으로 검색할 수 있는 api를 작성했습니다
그리고 추가 작업으로 급상승유저와 조회수랭킹 기반을 작업했습니다
> Feature: ranking search

- backend/libs/const/expiration.ts
- backend/libs/const/index.ts
- backend/src/user/user.controller.ts
단순 fix ( 메소드명 및 변수 분리)
- findUserWithUpdateViews를 컨벤션에 맞게 findOne으로 수정
- API DELAY TIME을 const로 분리
> Feature: findUser 메소드 명을 컨벤션에 맞게 수정

- frontend/src/components/Filterbar/index.tsx
- frontend/src/components/Ranking/index.tsx
- frontend/src/components/common/Avatar/index.tsx
- frontend/src/components/common/Button/index.tsx
- frontend/src/components/common/CubeIcon/CubeIcon.stories.tsx
- frontend/src/components/common/CubeIcon/index.tsx
- frontend/src/components/common/LanguageIcon/LanguageIcon.stories.tsx
- frontend/src/components/common/LanguageIcon/index.tsx
- frontend/src/components/common/Searchbar/index.tsx
- frontend/src/components/common/Spinner/index.tsx
- story 누락 컴포넌트 story 작성 및 스토리북 docs 설정을 위한 타입 주석 추가 
- CubeIcon, LanguageIcon 컴포넌트 story작성
- 컴포넌트 props 타입 주석 추가
> Test: 컴포넌트 story 작성

- frontend/src/apis/ranking.ts
- frontend/src/pages/index.tsx
- frontend/src/type/response.ts
- 백엔드 ranking api엔드포인트와 response수정에 따라 프론트엔드 코드 수정
- api 요청 url 수정
- response type에 tier 추가 및 랭킹 데이터에 적용
> Fix: 백엔드 ranking API 변경에 따른 프론트엔드 수정

- backend/src/user/user.controller.ts
- backend/src/user/user.service.ts
default branch가 없는 경우를 예외처리
- close #88
> Fix: default branch가 없는 레포 예외처리

- backend/src/ranking/ranking.controller.ts
- backend/src/ranking/ranking.service.ts
- backend/src/user/user.controller.ts
- backend/src/user/user.repository.ts
- backend/src/user/user.service.ts
pagination 적용이 빠져있던 api에 pagination 적용
사용되지 않던 user findAll api 삭제
> Refactor: findAllByUsername에 페이지네이션 적용

- backend/src/user/user.schema.ts
소수점을 포함한 점수가 사용성을 낮춘다고 판한하여 정수형으로 변환
> fix: 점수를 정수형으로 변환

- backend/src/user/user.controller.ts
- backend/src/user/user.repository.ts
- backend/src/user/user.service.ts
시간가중치를 1년이 지날때 절반이되는 지수함수를 적용
점수산정 중복코드를 함수로 분리
close #110 
close #112
> Feature: 점수 산정에 시간가중치 적용

- backend/src/user/user.service.ts
> fix: node_id값이 적용되지 않아 user commit filter 되지 않던 문제 수정

- frontend/src/components/Header/index.tsx
- frontend/src/hooks/useQueryData.ts
- frontend/src/pages/404.tsx
- frontend/src/pages/about.tsx
- frontend/src/pages/index.tsx
- frontend/src/pages/ranking.tsx
- frontend/src/styles/globalStyles.ts
프론트엔드 리팩토링 진행
- font color 스타일 전체 적용 방식 inherit를 통한 방식으로 변경
- 랭킹 페이지 serverSideProps 랭킹 데이터 prefetch 방식으로 변경
- 404, about 페이지 초기 로드시 클라이언트에서 refresh 요청 추가
- useQueryData 메모리 최적화 적용
- 헤더 컴포넌트 useQuery -> useQueryData로 user data 가져오게 수정
> Refactor: 프론트엔드 리팩토링

- backend/src/user/dto/user.dto.ts
- backend/src/user/user.schema.ts
- backend/src/user/user.service.ts
유저별 primary languages 정보 추가
점수산정 적용 repository 25개로 변경
close #125
close #124
> Feature: primary languages 정보 점수 산정시 추가

- backend/libs/consts/index.ts
- backend/src/auth/auth.module.ts
- backend/src/auth/auth.repository.ts
- backend/src/auth/auth.service.ts
- backend/src/main.ts
- backend/src/ranking/dto/ranking-pagination.dto.ts
- backend/src/ranking/dto/ranking-user.dto.ts
- backend/src/ranking/ranking.controller.ts
- backend/src/ranking/ranking.service.ts
- backend/src/user/dto/user.dto.ts
- backend/src/user/user.controller.ts
- backend/src/user/user.repository.ts
- backend/src/user/user.service.ts
- pagination API 로직 변경 및 metadata 추가
- pagination API aggregate로 변경
- pagination routing을 위한 meta데이터 계산
> Feature: pagination meta

- backend/src/ranking/dto/ranking-language.dto.ts
- backend/src/ranking/ranking.controller.ts
- backend/src/ranking/ranking.service.ts
- backend/src/user/user.repository.ts
가장 많이 사용되고 있는 언어 순위 api
- close #126
> feat: getMostUsedLanguages api

- backend/src/ranking/dto/ranking-user.dto.ts
- backend/src/user/user.service.ts
오름차순정렬을 내림차순으로 수정
rankingUserDto에 primaryLanguages 정보 포함
close #132
> fix: 오름차순으로 정렬되던걸 내림차순으로 수정

- backend/libs/consts/index.ts
- backend/src/ranking/ranking.service.ts
- 페이지네이션의 페이지 단위를 1~10, 11~20처럼 10단위로 고정
> Fix: pagination

- frontend/src/apis/ranking.ts
- frontend/src/components/Pagination/Arrow.stories.tsx
- frontend/src/components/Pagination/Arrow.tsx
- frontend/src/components/Pagination/Pagination.stories.tsx
- frontend/src/components/Pagination/index.tsx
- frontend/src/components/common/LanguageIcon/index.tsx
- frontend/src/pages/_app.tsx
- frontend/src/pages/index.tsx
- frontend/src/pages/profile/404.tsx
- frontend/src/pages/ranking.tsx
- frontend/src/utils/constants.ts
- 랭킹 페이지 페이지네이션 추가
- 사용자 검색시 not found 페이지 추가
- close #134
- close #116 
- close #69 
- 페이지네이션 컴포넌트 추가
- 랭킹페이지 페이지네이션 추가
- 사용자 검색시 not found 페이지 추가
- 랭킹페이지 랭킹컴포넌트 글자색 메인페이지랑 동일하게함
> Feature: ranking 페이지 페이지네이션 추가

- backend/src/user/user.service.ts
> fix: repositoryScore가 0점인 경우 언어에 불포함

- .github/workflows/build.yml
- .gitignore
- backend/.dockerignore
- backend/Dockerfile
- backend/docker-compose.yml
- backend/package.json
- backend/src/app.module.ts
main에 머지될때 빌드하여 docker hub에 업로드하는 actions 작성
docker-compose를 이용한 도커라이징
- close #23
> CI: docker compose

- frontend/public/locales/en/profile.json
- frontend/public/locales/ko/profile.json
- frontend/src/components/Profile/CommitHistory/index.tsx
- frontend/src/components/Profile/EXPbar/index.tsx
- frontend/src/components/Profile/ProfileCard/index.tsx
- frontend/src/components/Profile/index.ts
- frontend/src/pages/profile/[username].tsx
- frontend/src/utils/constants.ts
랭킹페이지 커밋 히스토리 컴포넌트 구현
- #117
- month 상수 배열 추가
- 커밋 내역 컴포넌트 작성 및 레이아웃 구현
> Feature: commit history 컴포넌트 구현

- frontend/src/pages/profile/[username].tsx
- frontend/src/pages/ranking.tsx
프로필 페이지 오류 수정
- 랭킹 점수 없을 시 오류 수정
-  getServerSideProps에 profile 추가
> Fix: profile 버그 수정

- frontend/src/components/common/Searchbar/Searchbar.stories.tsx
- frontend/src/components/common/Searchbar/index.tsx
- frontend/src/hooks/useDebounce.ts
- frontend/src/pages/about.tsx
useDebounce hook 추가
- useDebounce hook 추가
> Feature: usedebounce

- backend/src/auth/auth.controller.ts
- backend/src/ranking/dto/ranking-user.dto.ts
- backend/src/ranking/ranking.controller.ts
- backend/src/ranking/ranking.service.ts
- backend/src/user/dto/auto-complete.dto.ts
- backend/src/user/dto/history.dto.ts
- backend/src/user/dto/organization.dto.ts
- backend/src/user/dto/pinned-repository.dto.ts
- backend/src/user/dto/user.dto.ts
- backend/src/user/dto/user.profile.dto.ts
- backend/src/user/user.controller.ts
- backend/src/user/user.repository.ts
- backend/src/user/user.schema.ts
- backend/src/user/user.service.ts
- 유저 contribution history 가져와서 가공 로직 추가 (stat정보들 및 잔디 정보)
- 유저 pinned repositories 가져와서 가공 로직 추가
- 유저의 전체 등수, 티어 내 등수 계산 로직 추가
- 유저 업데이트하는 로직 refactoring
- 유저의 contribution, pinned repo, 스코어 계산하는 부분들을 함수로 분리
> Feature: profile api

- frontend/src/apis/ranking.ts
- frontend/src/components/Ranking/RankingSearchbar/index.tsx
- frontend/src/components/common/Searchbar/AutoComplete.tsx
- frontend/src/components/common/Searchbar/AutoComplete/AutoComplete.tsx
- frontend/src/components/common/Searchbar/AutoComplete/index.tsx
- frontend/src/components/common/Searchbar/index.tsx
- frontend/src/hooks/index.ts
- frontend/src/hooks/useAutoComplete.ts
- frontend/src/hooks/useInput.ts
- frontend/src/pages/index.tsx
- frontend/src/pages/ranking.tsx
- frontend/src/utils/constants.ts
메인페이지 검색어 자동완성 구현
- close #162
- 검색어 입력시 자동완성 리스트 렌더링
- 검색어 자동완성 리스트 포커스 방향키 컨트롤 구현
- 검색어 자동완성 로직 `useAutoComplete` 커스텀훅으로 분리
- 자동완성 검색바, default 검색바 로직 분리 및 리팩토링
> Feature: 검색어 자동 완성

- backend/src/user/user.repository.ts
조회수 랭킹 정렬 기준이 views로 되어있는데 스키마 변경에 따라 dailyViews로 변경
> fix: mostViewedRanking 정렬기준

- frontend/src/components/Ranking/index.tsx
- frontend/src/pages/index.tsx
- frontend/src/pages/ranking.tsx
- 유저 클릭시 프로필 페이지로 이동
- Ranking.Row 컴포넌트에 onClick 함수 추가
> Feature: 유저 클릭시 프로필 페이지로 이동

- backend/src/user/dto/auto-complete.dto.ts
- backend/src/user/dto/organization.dto.ts
- backend/src/user/dto/pinned-repository.dto.ts
> Fix: organizaiton dto 수정

- backend/src/user/user.service.ts
> Fix: followersScore 내림

- frontend/src/apis/users.ts
- frontend/src/components/common/Searchbar/AutoComplete/AutoComplete.tsx
- frontend/src/hooks/useAutoComplete.ts
- frontend/src/type/response.ts
검색어 입력시 자동완성 리스트가 뜨지 않던 현상 수정
- close #172
- 백엔드 API 변경에 맞추어 검색 자동완성 시 호출하는 API 함수 변경
> Fix: 검색 자동완성 유저 데이터 fetching API 변경

- frontend/src/pages/index.tsx
- frontend/src/type/response.ts
검색 자동완성 오류 수정
- router 변수 누락 수정
- type 누락 id props 수정
> Fix: 검색 자동완성 오류 수정

- backend/src/user/user.service.ts
- backend/src/user/utils/query.ts
> refactor: graphql query 별도 파일로 분리

- backend/src/auth/auth.service.ts
> Fix: 로그인 시 배포 환경에서 cookie 도메인이 잘못 설정되는 문제 해결

- frontend/public/locales/ko/404.json
- frontend/src/components/Header/index.tsx
- frontend/src/components/Profile/PinnedRepository/index.tsx
프론트엔드 이슈 해결
- close #194 
- close #191 
- close #187 
- 404페이지 오타수정
- Repository 링크 연결
- 국제화 버튼 인식 범위 수정
> Fix: 프론트엔드 이슈 해결

- backend/src/user/user.service.ts
> Fix: db에 없는 유저를 호출할때 update된 유저 정보를 반환하도록 수정

- .github/workflows/build.yml
- frontend/.dockerignore
- frontend/Dockerfile
- frontend/package.json
> CI: frontend deploy

- backend/src/batch/batch.service.ts
- backend/src/user/user.service.ts
> fix: user.scoreHistory가 비었을시 예외처리

- backend/src/user/user.service.ts
> Fix: 유저 정보 새로고침시 userInfo 변경

- backend/libs/consts/index.ts
- backend/src/user/dto/rank.dto.ts
- backend/src/user/user.repository.ts
- backend/src/user/user.service.ts
- 계산된 유저 (전체/티어 내) 등수 정보 캐싱
- close #109
> Feature: score cache

- backend/libs/consts/index.ts
- backend/src/batch/batch.service.ts
- backend/src/user/user.controller.ts
- backend/src/user/user.service.ts
-  github api 호출 시, 빠르게 호출하면 secondary limit이 발생하는 이슈 해결
close #158
> Feature: GitHub api delay

- frontend/src/apis/ranking.ts
- frontend/src/components/Filterbar/index.tsx
- frontend/src/components/Header/index.tsx
- frontend/src/components/Pagination/index.tsx
- frontend/src/pages/ranking.tsx
- frontend/src/utils/utils.ts
랭킹 url 필터링 적용
* close #181 
* 랭킹 필터링 방식 state 기반 -> url 기반으로 수정
* 올바른 url인지 확인하기위한 queryValidator 함수 추가
> Feature: 랭킹 url 필터링 적용

- backend/libs/utils/utils.ts
- backend/src/user/dto/user.dto.ts
- backend/src/user/user.service.ts
> Refactor: Exp 산정 로직 함수화

- backend/libs/common/filters/http-exception.filter.ts
- backend/libs/utils/logger.ts
- backend/src/main.ts
> Fix: log파일에 시간 정보 및 stack 정보 기록

- .github/workflows/build.yml
- frontend/.dockerignore
- frontend/Dockerfile
- frontend/package.json
- frontend/yarn.lock
- 도커 빌드 전 .env.prodcution 생성
- dockerfile CMD 명령어 수정
> CI: frontend 배포 시 환경변수 관련 설정

- frontend/src/components/Header/index.tsx
- frontend/src/pages/404.tsx
- frontend/src/pages/about.tsx
SSG 페이지에서 로그인 유지 사용자 경험 개선
이제 미로그인 상태가 뜨지 않고 빈 공간이 렌더링되다가 표시됨
- Header 컴포넌트에서 refresh 요청을 하는 방식으로 개선
> Refactor: 로그인 유지 개선

- backend/src/auth/auth.controller.ts
- backend/src/user/user.service.ts
> Fix: scoreHistory 새로 생긴 유저인 경우에만 추가 / updateAllUsers시 scoreHistory 변경

- frontend/src/components/Ranking/OverallRanking/index.tsx
- frontend/src/components/Ranking/RisingRanking/index.tsx
- frontend/src/components/Ranking/ViewsRanking/index.tsx
- frontend/src/components/common/Dropdown/index.tsx
ranking component 랭킹 중앙 정렬
- close #243
> Style: ranking component 랭킹 중앙 정렬

- frontend/src/components/Profile/PinnedRepository/index.tsx
- frontend/src/components/Ranking/OverallRanking/index.tsx
- frontend/src/components/common/Avatar/index.tsx
- frontend/src/pages/index.tsx
- frontend/src/pages/ranking.tsx
- frontend/src/type/response.ts
- frontend/src/utils/fonts.ts
프론트엔드 오타, 스타일 수정 및 개선
- pinned repository 설명 height 수정 -> height가 글자 길이보다 커서 ellipsis아래로 글자가 보이는 문제  
- avatar image priority 속성 큰 아바타일 경우만 on 
- 네이밍 오타 수정
- 사용하지 않는 Noto Sans KR 폰트 제거
> Fix: 프론트엔드 수정

- frontend/public/locales/en/meta.json
- frontend/public/locales/ko/meta.json
- frontend/src/utils/utils.ts
meta 태그 텍스트 간략하게 수정
- meta title 속성 텍스트 간략하게 수정
- 프로필 meta description 사용자명 제거
> Refactor: meta태그 텍스트 수정

- backend/libs/common/decorators/user-github-id.decorator.ts
- backend/src/user/user.controller.ts
로그인된 유저만의 기능을 통해 유저의 회원가입을 유도 할 수 있도록 함
frontend 에도 적용되어야함
@asdf99245 @tunggary
> feat: 본인의 프로필 업데이트는 시간제한 없음

- .github/workflows/build.yml
배포할때 release와 tag를 자동으로 생성하고 생성한 release 버전이름을 기준으로 docker tag도 생성
*주의 main merge 할때 commit 명에 버전이름 포함해야함
> CI: create release

- frontend/public/locales/en/ranking.json
- frontend/public/locales/ko/ranking.json
- frontend/src/hooks/useInput.ts
- frontend/src/pages/ranking.tsx
- 프론트엔드 리팩토링
- close #254 
- close #251
> Refactor: ranking and searchbar

- backend/src/user/user.service.ts
> Fix: score값에 null이 들어가던 오류 수정

- backend/src/batch/batch.service.ts
> Fix: 사용되지 않는 변수 제거

- frontend/src/pages/index.tsx
메인페이지 router 버그 수정
- close #275
> fix: router bug

- frontend/src/components/common/Searchbar/AutoComplete/index.tsx
- frontend/src/pages/index.tsx
- 검색시 로딩 과정 수정
- close #278 
- 로딩 UI 변경
- 메인페이지에서 검색시에만 로딩뜨도록 함
> Refactor: 검색시 로딩 과정 수정

- backend/src/auth/auth.controller.ts
- backend/src/auth/auth.service.ts
- 동일 브라우저에서 매우 짧은 주기로 새로고침 시 RTR 로직 특성 상 로그인 풀리는 문제  발생
- 일단 RTR을 걷어내기로 결정
> Refactor: Refresh 시 RTR 문제 해결

- backend/src/user/user.service.ts
> feat: total contribution 점수에 포함

- backend/src/user/user.repository.ts
- backend/src/user/user.service.ts
- 업데이트 로직 수행 시 유저 등수 정보 refresh
> Feature: 유저 등수 정보 refresh

- backend/src/user/user.service.ts
> Fix: 불필요하게 업데이트되는 user 정보 로직 제거

- frontend/src/apis/auth.ts
- frontend/src/pages/api/og-image.tsx
사용자 이름이 긴 경우 미리보기 이미지 깨지는 버그 수정
> Refactor: og image 버그 수정

- frontend/src/components/Header/index.tsx
- frontend/src/hooks/useQueryData.ts
- frontend/src/pages/404.tsx
- frontend/src/pages/about.tsx
랭킹 페이지에서 로그인 시 404페이지로 이동하던 오류 수정
SSG페이지에서 로그인 시 미로그인 버튼이 표시되던 현상 수정 
- close #250
- 랭킹페이지에서 로그인 후 callback시 돌아갈 pathname router.asPath로 저장
- 헤더에서 refresh요청을 하는 방법으로 수정
- refresh요청중 빈 공간 표시
> Fix: 로그인 유지

- backend/src/batch/batch.service.ts
- backend/src/user/user.service.ts
> Refactor: 오늘날짜와 같은 경우 scoreHistory 업데이트

- backend/src/user/user.controller.ts
- backend/src/user/user.service.ts
- 업데이트 실패 유저 시 204 반환
- 업데이트 실패 유저는 조회수 상승 X
- 업데이트 실패 유저 수동 새로고침 시 딜레이 추가
> Feature: 업데이트 실패 유저 조회 시 예외 처리

- frontend/src/components/Profile/Statistic/index.tsx
- frontend/src/pages/profile/[username].tsx
data.history undefined 타입 오류 수정
> Fix: history type error 수정

- backend/libs/common/filters/http-exception.filter.ts
- backend/src/user/user.service.ts
- logger에 업데이트 실패 등 500대 에러나 예기치 못한 에러 잡도록 수정
- score history로 인해 새로운 유저 등록이 정상적으로 되지 않는 문제 해결
> Fix: update bug

- backend/src/user/user.service.ts
> fix: 유저 업데이트 실패 시 log에 이름 기록

- backend/src/user/user.service.ts
> Fix: date timezone 설정

- frontend/src/components/Ranking/LanguageRanking/index.tsx
- frontend/src/components/Ranking/RankingTable/index.tsx
- frontend/src/pages/ranking.tsx
> Fix: 랭킹 컴포넌트 UI 깨지는 문제 해결

- frontend/package.json
- frontend/public/robots.txt
- frontend/src/components/common/HeadMeta/index.tsx
- frontend/src/pages/sitemap.tsx
- frontend/yarn.lock
- robots, sitemap 설정
- close #321
> Feature: robots, sitemap 설정

- frontend/src/components/Profile/Statistic/index.tsx
- frontend/src/utils/utils.ts
- function name 수정
- close #316 
- hook을 포함하는 함수 이름 접두사 use추가
> Refactor: function name 수정

- frontend/next.config.js
- frontend/src/components/common/LanguageIcon/index.tsx
- frontend/src/utils/constants.ts
- frontend/src/utils/utils.ts
-  language icon 소스 변경
- close #317 
- 프로그래밍 언어 아이콘 소스를 devicon에서 아이콘을 더 많이 지원하는 vscode icons로 변경
> Refactor: language icon 소스 변경

- frontend/src/utils/utils.ts
랭킹페이지 url 필터링 수정
- /ranking으로 접근시 page=1, tier=all 로 필터링 될 수 있게함
> Refactor: 랭킹페이지 url 필터링 수정

- frontend/src/pages/index.tsx
- frontend/src/pages/profile/[username].tsx
- frontend/src/pages/ranking.tsx
- frontend/src/utils/utils.ts
- frontend/src/utils/wrapper.ts
ssrWrapper, ssgWrapper 함수 구조 리팩토링
- close #312
- wrapper propsData 타입 제네릭 적용 
- wrapper redirect 로직 try catch로 분리
- profile 페이지 ssrWrapper 적용
> Refactor: SSR, SSG wrapper HOF 리팩토링

- backend/src/ranking/dto/ranking-user.dto.ts
- backend/src/ranking/ranking.service.ts
- backend/src/user/dto/user.dto.ts
- backend/src/user/user.repository.ts
- backend/src/user/user.schema.ts
> Feature: tierrank cache

- frontend/src/utils/wrapper.ts
wrapper callback 반환값 없을 때 오류 해결 
wrapper 반환값 타입 void 처리
> Fix: wrapper callback 반환값 없을 때 타입 void 처리

- frontend/src/components/Ranking/RankingTable/index.tsx
- frontend/src/pages/ranking.tsx
- frontend/src/type/response.ts
- frontend/src/utils/constants.ts
랭킹페이지, 랭킹 컴포넌트 리팩토링
- 랭킹페이지에서 순위가 인덱스가 아닌 실제 순위로 보이도록 수정
- 랭킹컴포넌트 onClick 함수 없을 시, 즉 실제 클릭시 작동하지 않을 경우 호버 스타일 적용 안되도록 수정
- language icon rust 이미지 수정
> Refactor: 랭킹페이지, 랭킹 컴포넌트

- frontend/src/components/Ranking/LanguageRanking/index.tsx
- frontend/src/components/Ranking/OverallRanking/index.tsx
- frontend/src/components/Ranking/RankingTable/index.tsx
- frontend/src/components/Ranking/RisingRanking/index.tsx
- frontend/src/components/Ranking/ViewsRanking/index.tsx
- frontend/src/pages/ranking.tsx
> Refactor: RankingTable 컴포넌트 Body 추가

- frontend/src/utils/wrapper.ts
> Feature: header 세팅

- frontend/src/components/Profile/CommitHistory/index.tsx
- frontend/src/components/Profile/PinnedRepository/index.tsx
- frontend/src/components/Ranking/RisingRanking/index.tsx
- frontend/src/utils/constants.ts
- frontend/src/utils/utils.ts
- Mapping 함수 제거하고 Intl로 month label 설정
> Refactor: month label 

- .gitignore
- frontend/src/components/Profile/ProfileRefreshButton/index.tsx
- frontend/src/hooks/useInterval.ts
interval 때문에 업데이트 버튼이 무한으로 리렌더링 되는 현상 수정
- close #237
- useInterval 훅  `isActivate` 속성을 통해 비활성시 interval 동작 블로킹
> Fix: 업데이트 버튼 무한 rerender 수정

- backend/libs/consts/index.ts
- backend/src/user/utils/query.ts
커밋 점수 산정을 3년으로 제한
추후 최적화를 통해 이 기한을 늘려나가야함
> Fix: fork commit limit
